# Generated by Django 6.0.3 on 2026-06-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_amenity_rooms_bookings_hotel_payment_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
