# Generated by Django 6.0.3 on 2026-07-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
