# Generated by Django 6.0.3 on 2026-08-12 03:27

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_guests_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookings',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('room', '='), (models.Func('check_in_date', 'check_out_date', function='daterange'), '&&')], name='prevent_overlapping_room_bookings'),
        ),
    ]
