# Generated by Django 6.0.3 on 2026-09-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookings_prevent_overlapping_room_bookings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookings',
            name='prevent_overlapping_room_bookings',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
