# Generated by Django 6.0.3 on 2026-09-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_guests_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='actual_check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='actual_check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
