# Generated by Django 6.0.3 on 2026-09-20 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('bed_count', models.IntegerField()),
                ('bed_type', models.CharField(max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.PositiveIntegerField(default=1)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
            options={
                'db_table': 'room_types',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.roomtypes'),
        ),
    ]
