# Generated by Django 6.0.3 on 2026-09-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_roomtypes_bookings_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.rooms'),
        ),
    ]
